
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author shubh
 */
public class FontF extends javax.swing.JFrame {

    /**
     * Creates new form FontF
     */
    static GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
    static String[] fontNames;
    static Font f = null;

    public FontF() {
        initComponents();
        myinitComponents();
        setIconImage();

    }

    private void myinitComponents() {

        fontNames = ge.getAvailableFontFamilyNames();
        fontlist.setListData(fontNames);
        String[] size = new String[40];
        int j = 2;
        for (int i = 0; i < 40; i++) {
            size[i] = String.valueOf(j);
            j += 2;
        }
        sizelist.setListData(size);
        String[] style = new String[3];
        style[0] = "REGULAR";
        style[1] = "BOLD";
        style[2] = "ITALIC";
        stylelist.setListData(style);
        fontlist.setSelectedIndex(2);
        stylelist.setSelectedIndex(0);
        sizelist.setSelectedIndex(5);
        fonttext.setText(fontlist.getSelectedValue());
        styletext.setText(stylelist.getSelectedValue());
        sizetext.setText(sizelist.getSelectedValue());
        String font = fontlist.getSelectedValue();
        f = new Font(font, Font.PLAIN, 12);
        previewlbl.setFont(f);
        previewlbl.setText("AaBbCc");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fontlist = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        stylelist = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        sizelist = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        fonttext = new javax.swing.JTextField();
        styletext = new javax.swing.JTextField();
        sizetext = new javax.swing.JTextField();
        okbutt = new javax.swing.JButton();
        canclebutt = new javax.swing.JButton();
        previewlbl = new javax.swing.JLabel();

        jLabel1.setText("Font:");

        fontlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fontlistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(fontlist);

        jLabel2.setText("Font Style:");

        stylelist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stylelistMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(stylelist);

        sizelist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sizelistMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(sizelist);

        jLabel3.setText("Size:");

        fonttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fonttextActionPerformed(evt);
            }
        });

        styletext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                styletextActionPerformed(evt);
            }
        });

        sizetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizetextActionPerformed(evt);
            }
        });

        okbutt.setText("OK");
        okbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbuttActionPerformed(evt);
            }
        });

        canclebutt.setText("Cancle");
        canclebutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canclebuttActionPerformed(evt);
            }
        });

        previewlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(okbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(canclebutt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(fonttext, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(styletext, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(sizetext, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(previewlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, 0)
                        .addComponent(fonttext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(styletext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sizetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(previewlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okbutt)
                    .addComponent(canclebutt))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fonttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fonttextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fonttextActionPerformed

    private void styletextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_styletextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_styletextActionPerformed

    private void sizetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizetextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizetextActionPerformed

    private void okbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbuttActionPerformed
        try {
            int size = Integer.parseInt(sizetext.getText());
            if (size > 0) {
                txtfile.txtarea.setFont(f);
                FontF.this.hide();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Invaid size");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Invaid size");
        }

    }//GEN-LAST:event_okbuttActionPerformed

    private void canclebuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canclebuttActionPerformed
        FontF.this.hide();
    }//GEN-LAST:event_canclebuttActionPerformed

    private void fontlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fontlistMouseClicked

        fonttext.setText(fontlist.getSelectedValue());
        String font = fontlist.getSelectedValue();
        String style = stylelist.getSelectedValue();
        try {
            int size = Integer.parseInt(sizetext.getText());
            if (size > 0) {
                if ("REGULAR".equals(style)) {
                    f = new Font(font, Font.PLAIN, size);
                } else if ("BOLD".equals(style)) {
                    f = new Font(font, Font.BOLD, size);
                } else if ("ITALIC".equals(style)) {
                    f = new Font(font, Font.ITALIC, size);
                }
                previewlbl.setFont(f);
                previewlbl.setText("AaBbCc");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Invaid size");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Invaid size");
        }

        //int style = f.getStyle();
        //String[] fontStyle = ge.;
    }//GEN-LAST:event_fontlistMouseClicked

    private void stylelistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stylelistMouseClicked
        styletext.setText(stylelist.getSelectedValue());
        String font = fontlist.getSelectedValue();
        String style = stylelist.getSelectedValue();
        try {
            int size = Integer.parseInt(sizetext.getText());
            if (size > 0) {
                if ("REGULAR".equals(style)) {
                    f = new Font(font, Font.PLAIN, size);
                } else if ("BOLD".equals(style)) {
                    f = new Font(font, Font.BOLD, size);
                } else if ("ITALIC".equals(style)) {
                    f = new Font(font, Font.ITALIC, size);
                }
                previewlbl.setFont(f);
                previewlbl.setText("AaBbCc");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Invaid size");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Invaid size");
        }

    }//GEN-LAST:event_stylelistMouseClicked

    private void sizelistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sizelistMouseClicked
        sizetext.setText(sizelist.getSelectedValue());
        String font = fontlist.getSelectedValue();
        String style = stylelist.getSelectedValue();
        try {
            int size = Integer.parseInt(sizetext.getText());
            if (size > 0) {
                if ("REGULAR".equals(style)) {
                    f = new Font(font, Font.PLAIN, size);
                } else if ("BOLD".equals(style)) {
                    f = new Font(font, Font.BOLD, size);
                } else if ("ITALIC".equals(style)) {
                    f = new Font(font, Font.ITALIC, size);
                }
                previewlbl.setFont(f);
                previewlbl.setText("AaBbCc");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Invaid size");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Invaid size");
        }
    }//GEN-LAST:event_sizelistMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {

        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FontF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canclebutt;
    private javax.swing.JList<String> fontlist;
    private javax.swing.JTextField fonttext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton okbutt;
    private javax.swing.JLabel previewlbl;
    private javax.swing.JList<String> sizelist;
    private javax.swing.JTextField sizetext;
    private javax.swing.JList<String> stylelist;
    private javax.swing.JTextField styletext;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
}
